#! /usr/bin/env bash

if [ -z "$JEKYLL_EC_PRIVATEKEY" ]; then
  echo "JEKYLL_EC_PRIVATEKEY is not set"
  # export  JEKYLL_EC_PRIVATEKEY='L28e3HZofHGGIr3ZZTIPhtfBfTbvxedNYF1xpJdx5PA='
  exit 1

  echo 'JEKYLL_EC_PRIVATEKEY is now set to DEBUG value'
fi

rm -rf tags
bundle exec jekyll clean
bundle exec jekyll build --future